default: &default
  name: 'Ondokuz Mayıs Üniversitesi'
  abbreviation: 'omu'
  host: 'https://nokul.app.omu.sh'
  email:
    domain: 'omu.edu.tr'
    default_from: 'noreply@baum.omu.edu.tr'
    support: 'hotline@baum.omu.edu.tr'

production: *default
development: *default
test: *default
