# frozen_string_literal: true

require 'pathname'

PLUGINS_DIR = Pathname.new File.expand_path('../..', __dir__)

source 'https://rubygems.org'

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gemspec

gem 'nokul-support', path: PLUGINS_DIR.join('support')
gem 'nokul-tenant', path: PLUGINS_DIR.join('tenant', 'common')

group :test do
  gem 'minitest-focus'
  gem 'sqlite3'
end
