# frozen_string_literal: true

module Codeable
  def code(comment = nil)
    coder = Tenant::Unit::Coder.new Tenant.path(collection.coder)
    self.class.store coder.code(self).sort_by(&:code), comment: comment
  end
end

ALL.include Codeable

namespace :tenant do
  namespace :units do
    desc 'Code units'
    task :code do
      Support.abort_on_yaml_syntax_errors do
        aggregated_units = ALL.new [YOK, DET, UNI].map(&:load).flatten
        aggregated_units.code 'AUTOGENERATED FROM SOURCES. DO NOT EDIT.'
      end
    end
  end
end
