# frozen_string_literal: true

CalendarTitle.create(name: 'Açılan derslerin ilanı')
CalendarTitle.create(name: 'Ders Kayıtları')
CalendarTitle.create(name: 'Derslerin Başlaması')
CalendarTitle.create(name: 'Ders Ekleme ve Bırakma')
CalendarTitle.create(name: 'Derslerin Bitimi')
CalendarTitle.create(name: 'Ara Sınav Haftası')
CalendarTitle.create(name: 'Yarıyıl Sonu Sınav Haftası')
CalendarTitle.create(name: 'Bütünleme Sınav Haftası')
CalendarTitle.create(name: 'Çift Anadal ve Yandal Başvuruları')
CalendarTitle.create(name: 'Çift Anadal ve Yandal Başvurularının Birimlerce Değerlendirilmesi ve İlanı')
CalendarTitle.create(name: 'Zorunlu Hazırlık Sınıfları Yabancı Dil Yeterlik Sınavı')
CalendarTitle.create(name: 'Yeterlik Sınav Sonuçlarının İlanı')
CalendarTitle.create(name: 'Hazırlık Sınıfları İçin Düzey Belirleme Sınavı')
CalendarTitle.create(name: 'Öğrencilerin WEB\'de Ders Kayıtları (Çiftanadal, Yandal Öğrencileri Dahil)')
CalendarTitle.create(name: 'Yabancı Dil Muafiyet Sınavları (5/i Dersleri İçin)')
CalendarTitle.create(name: 'Danışman Onay İşlemleri')
CalendarTitle.create(name: 'Mazeretli Ders Kaydı Başvuruları Son Günü')
CalendarTitle.create(name: 'Ara Mazeret Sınav Başvurusu Son Günü')
CalendarTitle.create(name: 'Yarıyıl Sonu Sınav Sonuçlarının İnternetten Girilmesinin Son Günü ve Sonuçların İlanı')
CalendarTitle.create(name: 'Bütünleme Sınav Sonuçlarının İnternetten Girilmesinin Son Günü')
CalendarTitle.create(name: 'Tek Ders Sınav Müracaatları')
CalendarTitle.create(name: 'Tek Ders Sınavları')
CalendarTitle.create(name: 'Tek Ders Sınav Sonuçlarının ÖİDB\'ye Gönderilmesi')
CalendarTitle.create(name: 'Doktora Yeterlik Sınavları')
CalendarTitle.create(name: 'Dönem Projesi Teslimi')
CalendarTitle.create(name: 'Öğrencilerin WEB\'de Ders Kayıtları')
CalendarTitle.create(name: 'Ek Sınav Müracaatlarının Son Günü (Önlisans öğrencileri için)')
CalendarTitle.create(name: 'Ek Sınav Tarihleri (Önlisans öğrencileri için)')
CalendarTitle.create(name: 'Ek Sınav Sonuçlarının ÖİDB\'ye Gönderilmesi')
AcademicTerm.create(year: '2017 - 2018', term: 'fall')
AcademicTerm.create(year: '2017 - 2018', term: 'spring')
AcademicTerm.create(year: '2017 - 2018', term: 'summer')
AcademicTerm.create(year: '2018 - 2019', term: 'fall')
AcademicTerm.create(year: '2018 - 2019', term: 'spring')
AcademicTerm.create(year: '2018 - 2019', term: 'summer')
CalendarType.create(name: 'Lisans - Önlisans')
CalendarType.create(name: 'Yüksek Lisans')
CalendarType.create(name: 'Ali Fuat Başgil Hukuk Fakültesi')
CalendarType.create(name: 'Yabancı Diller Yüksekokulu')
CalendarType.create(name: 'Tıp Fakültesi')
CalendarType.create(name: 'Diş Hekimliği Fakültesi (1-2-3. Sınıflar)')
CalendarType.create(name: 'Diş Hekimliği Fakültesi (4-5. Sınıflar)')
CalendarType.create(name: 'Veteriner Fakültesi')
CalendarType.create(name: 'UZEM Önlisans/Lisans')
CalendarType.create(name: 'UZEM Lisansüstü')
CalendarType.create(name: 'Yaz Dönemi')
CalendarType.create(name: 'Öğrenci')
CalendarTitleType.create(type: CalendarType.first, title: CalendarTitle.all.sample, status: 'active')
CalendarTitleType.create(type: CalendarType.first, title: CalendarTitle.all.sample, status: 'active')
CalendarTitleType.create(type: CalendarType.first, title: CalendarTitle.all.sample, status: 'active')
CalendarTitleType.create(type: CalendarType.first, title: CalendarTitle.all.sample, status: 'active')
CalendarTitleType.create(type: CalendarType.first, title: CalendarTitle.all.sample, status: 'active')
CalendarTitleType.create(type: CalendarType.first, title: CalendarTitle.all.sample, status: 'active')
CalendarTitleType.create(type: CalendarType.first, title: CalendarTitle.all.sample, status: 'active')
CalendarTitleType.create(type: CalendarType.first, title: CalendarTitle.all.sample, status: 'active')
CalendarTitleType.create(type: CalendarType.first, title: CalendarTitle.all.sample, status: 'active')
CalendarTitleType.create(type: CalendarType.first, title: CalendarTitle.all.sample, status: 'active')
CalendarTitleType.create(type: CalendarType.first, title: CalendarTitle.all.sample, status: 'active')
CalendarTitleType.create(type: CalendarType.first, title: CalendarTitle.all.sample, status: 'passive')
CalendarTitleType.create(type: CalendarType.first, title: CalendarTitle.all.sample, status: 'passive')
CalendarTitleType.create(type: CalendarType.first, title: CalendarTitle.all.sample, status: 'passive')
CalendarTitleType.create(type: CalendarType.first, title: CalendarTitle.all.sample, status: 'passive')
CalendarTitleType.create(type: CalendarType.first, title: CalendarTitle.all.sample, status: 'passive')
CalendarTitleType.create(type: CalendarType.first, title: CalendarTitle.all.sample, status: 'passive')
CalendarTitleType.create(type: CalendarType.first, title: CalendarTitle.all.sample, status: 'passive')
CalendarTitleType.create(type: CalendarType.first, title: CalendarTitle.all.sample, status: 'passive')
CalendarTitleType.create(type: CalendarType.first, title: CalendarTitle.all.sample, status: 'passive')
CalendarTitleType.create(type: CalendarType.first, title: CalendarTitle.all.sample, status: 'passive')
CalendarTitleType.create(type: CalendarType.first, title: CalendarTitle.all.sample, status: 'passive')
CalendarTitleType.create(type: CalendarType.first, title: CalendarTitle.all.sample, status: 'passive')
CalendarTitleType.create(type: CalendarType.first, title: CalendarTitle.all.sample, status: 'passive')
