version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: "03:00"
    timezone: Europe/Istanbul
  open-pull-requests-limit: 10
  labels:
  - dependencies
  allow:
  - dependency-type: all
  ignore:
  - dependency-name: aws-partitions
    versions:
    - 1.418.0
    - 1.422.0
    - 1.424.0
    - 1.427.0
    - 1.428.0
    - 1.429.0
    - 1.432.0
    - 1.434.0
    - 1.441.0
    - 1.443.0
    - 1.445.0
  - dependency-name: twilio-ruby
    versions:
    - 5.46.0
    - 5.46.1
    - 5.47.0
    - 5.48.0
    - 5.49.0
    - 5.50.0
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: i18n
    versions:
    - 1.8.7
    - 1.8.8
    - 1.8.9
  - dependency-name: webdrivers
    versions:
    - 4.5.0
  - dependency-name: rack-mini-profiler
    versions:
    - 2.3.0
  - dependency-name: semantic_range
    versions:
    - 2.3.1
  commit-message:
    prefix: chore
    include: scope
  rebase-strategy: disabled
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "03:00"
    timezone: Europe/Istanbul
  open-pull-requests-limit: 10
  labels:
  - dependencies
  allow:
  - dependency-type: all
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: node-releases
    versions:
    - 1.1.69
    - 1.1.70
  - dependency-name: object.getownpropertydescriptors
    versions:
    - 2.1.1
  - dependency-name: browserslist
    versions:
    - 4.16.0
  commit-message:
    prefix: chore
    include: scope
  rebase-strategy: disabled
