linters:
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Style/FrozenStringLiteralComment:
        Enabled: false
      Layout/InitialIndentation:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Naming/FileName:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
      Layout/LineLength:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
      Rails/OutputSafety:
        Enabled: false
      Performance/ChainArrayAllocation:
        Exclude:
          - app/views/first_registration/registration_documents/_form.html.erb
          - app/views/layouts/builders/_form.html.erb
  SpaceAroundErbTag:
    enabled: true
  FinalNewline:
    enabled: true
  ErbSafety:
    # TODO: To be reviewed
    enabled: false
  RightTrim:
    enabled: false
  SelfClosingTag:
    enabled: true
  AllowedScriptType:
    enabled: true
    allowed_types:
      - 'application/json'
      - 'text/javascript'
      - 'text/html'
    allow_blank: false
    disallow_inline_scripts: false
