require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-minitest

inherit_from:
  - https://raw.githubusercontent.com/omu/omu/master/etc/rubocop/rubocop.yml
  - .rubocop_todo.yml


Lint/NonDeterministicRequireOrder:
  Exclude:
    - lib/nokul/tenant/tasks.rb
    - lib/nokul/tenant/tests.rb

Rails:
  Enabled: true
Rails/UnknownEnv:
  Environments:
    - development
    - production
    - test

Metrics/BlockLength:
  Exclude:
    - config/initializers/devise.rb
    - config/routes/**/*
    - lib/tasks/**/*.rake
Metrics/ClassLength:
  Exclude:
    - test/**/*.rb
    - app/models/unit.rb
    - app/models/user.rb

Naming/FileName:
  Exclude:
    - plugins/support/lib/nokul-*.rb
    - plugins/tenant/*/lib/nokul-*.rb

AllCops:
  TargetRubyVersion: 2.7
  # Do not exclude files from ALL COPS unless it's really necessary!
  Exclude:
    - app/controllers/concerns/yoksis_resource.rb
    - bin/**/*
    - tmp/**/*
    - db/schema.rb
    - db/migrate/*.rb
    - config/initializers/simple_form.rb
    - config/initializers/simple_form_bootstrap.rb
    - config/environments/*.rb
    - config/routes.rb
    - node_modules/**/*
    - Vagrantfile
    - vendor/bundle/**/*
    - plugins/**/dummy/bin/**
