# Common settings!
Style/AsciiComments:
  Description: 'Use only ascii symbols in comments.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#english-comments'
  Enabled: false
Metrics/LineLength:
  Max: 120
Documentation:
  Enabled: false

# Do not exclude files from ALL COPS unless it's really necessary!
AllCops:
  Exclude:
    - bin/**/*
    - vendor/bundle/**/*
    - db/schema.rb
    - db/migrate/*.rb
    - config/initializers/simple_form.rb
    - config/initializers/simple_form_bootstrap.rb
    - config/environments/development.rb
    - config/environments/production.rb
    - config/environments/test.rb
    - config/routes.rb
Metrics/BlockLength:
  Exclude:
    - "lib/tasks/**/*.rake"

# Put your WIP file specific configuration below this line, not under AllCops!
Metrics/AbcSize:
  Exclude:
    - app/validators/address_validator.rb
    - app/validators/identity_validator.rb
    - app/services/kps/omu/adres.rb
    - app/services/kps/omu/kimlik.rb
Metrics/MethodLength:
  Exclude:
    - app/services/kps/omu/adres.rb
    - app/services/kps/omu/kimlik.rb
Metrics/CyclomaticComplexity:
  Exclude:
    - app/services/kps/omu/adres.rb
    - app/services/kps/omu/kimlik.rb
Metrics/PerceivedComplexity:
  Exclude:
    - app/services/kps/omu/adres.rb
    - app/services/kps/omu/kimlik.rb