# Do not exclude files from ALL COPS unless it's really necessary!
AllCops:
  Exclude:
    - bin/**/*
    - vendor/bundle/**/*
    - db/schema.rb
    - db/migrate/*.rb
    - app/models/users/*.rb # TODO: WIP
    - app/models/unit.rb # TODO: WIP => has_many :responsibles
Style/AsciiComments:
  Description: 'Use only ascii symbols in comments.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#english-comments'
  Enabled: false
Metrics/LineLength:
  Max: 120
Documentation:
  Enabled: false

# Put your file specific configuration below this line, not under AllCops!
Metrics/BlockLength:
  Exclude:
    - config/environments/development.rb
    - "**/**/*.rake"
Metrics/AbcSize:
  Exclude:
    - app/services/kps/omu/adres.rb
    - app/services/kps/omu/kimlik.rb
Metrics/MethodLength:
  Exclude:
    - app/services/kps/omu/adres.rb
    - app/services/kps/omu/kimlik.rb
Metrics/CyclomaticComplexity:
  Exclude:
    - app/services/kps/omu/kimlik.rb
Metrics/PerceivedComplexity:
  Exclude:
    - app/services/kps/omu/kimlik.rb
Style/ClassAndModuleChildren:
  Exclude:
    - test/test_helper.rb