inherit_from:
  - .rubocop_todo.yml
  - https://raw.githubusercontent.com/omu/omu/master/etc/rubocop/rubocop.yml

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-minitest



Rails:
  Enabled: true
Rails/Delegate:
  Exclude:
    - lib/nokul/tenant/api.rb
Rails/UnknownEnv:
  Environments:
    - development
    - production
    - test
Rails/Output:
  Exclude:
    - lib/**/*.rb

Metrics/BlockLength:
  Exclude:
    - config/initializers/devise.rb
    - config/routes/**/*
    - lib/tasks/**/*.rake

Metrics/ClassLength:
  Exclude:
    - test/**/*.rb
    - app/models/unit.rb
    - app/models/user.rb

Metrics/AbcSize:
  Exclude:
    - lib/nokul/support/minitest/validation_helper.rb

Naming/FileName:
  Exclude:
    - lib/nokul-support.rb
    - lib/nokul-tenant.rb
    - lib/nokul-tenant-*.rb

Metrics/MethodLength:
  Exclude:
    - lib/nokul/support/minitest/validation_helper.rb

Style/MixinUsage:
  Exclude:
    - test/dummy/**/*

Lint/NonDeterministicRequireOrder:
  Exclude:
    - lib/nokul/tenant/tasks.rb
    - lib/nokul/tenant/tests.rb

AllCops:
  TargetRubyVersion: 2.7
  # Do not exclude files from ALL COPS unless it's really necessary!
  Exclude:
    - app/controllers/concerns/yoksis_resource.rb
    - bin/**/*
    - tmp/**/*
    - db/schema.rb
    - db/migrate/*.rb
    - config/initializers/simple_form.rb
    - config/initializers/simple_form_bootstrap.rb
    - config/environments/*.rb
    - config/routes.rb
    - node_modules/**/*
    - Vagrantfile
    - vendor/bundle/**/*
