Style/AsciiComments:
  Enabled: false
Style/Lambda:
  Enabled: false
Documentation:
  Enabled: false
Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - beta
Metrics/LineLength:
  Max: 120
  Exclude:
    - app/validators/employee_validator.rb # Won't fix
Metrics/BlockLength:
  Exclude:
    - config/routes/**/*
    - lib/tasks/**/*.rake # Won't fix
    - test/models/concerns/reference_validations_test.rb
Metrics/ClassLength:
  Exclude:
    - test/**/*.rb

# Do not exclude files from ALL COPS unless it's really necessary!
AllCops:
  Exclude:
    - bin/**/*
    - vendor/bundle/**/*
    - node_modules/**/*
    - db/schema.rb
    - db/migrate/*.rb
    - config/initializers/simple_form.rb
    - config/initializers/simple_form_bootstrap.rb
    - config/environments/*.rb
    - config/routes.rb
    - Vagrantfile
