Layout/LineLength:
  Exclude:
    - app/validators/employee_validator.rb

Metrics/ModuleLength:
  Exclude:
    - app/services/ldap/entity.rb

Naming/MethodName:
  Exclude:
    - app/services/ldap/entity.rb

Performance/ChainArrayAllocation:
  Exclude:
    - app/decorators/curriculum_semester_decorator.rb
    - app/jobs/yoksis/academic_credentials_save_job.rb
    - app/jobs/yoksis/articles_save_job.rb
    - app/jobs/yoksis/books_save_job.rb
    - app/jobs/yoksis/certifications_save_job.rb
    - app/jobs/yoksis/education_informations_save_job.rb
    - app/jobs/yoksis/papers_save_job.rb
    - app/jobs/yoksis/projects_save_job.rb
    - app/models/unit.rb
    - app/services/ldap/entity.rb
    - app/validators/available_course_lecturer_validator.rb
    - app/validators/course_evaluation_type_validator.rb
    - app/validators/learning_outcome_validator.rb
