Style/AsciiComments:
  Description: 'Use only ascii symbols in comments.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#english-comments'
  Enabled: false
Style/Lambda:
  Enabled: false
Documentation:
  Enabled: false
Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - beta
Metrics/LineLength:
  Max: 120
  Exclude:
    - app/validators/employee_validator.rb # Won't fix
Metrics/BlockLength:
  Exclude:
    - lib/tasks/**/*.rake # Won't fix
Metrics/ClassLength:
  Exclude:
    - test/**/*.rb

# Do not exclude files from ALL COPS unless it's really necessary!
AllCops:
  Exclude:
    - bin/**/*
    - vendor/bundle/**/*
    - db/schema.rb
    - db/migrate/*.rb
    - config/initializers/simple_form.rb
    - config/initializers/simple_form_bootstrap.rb
    - config/environments/*.rb
    - config/routes.rb
    - app/services/kps/omu/adres.rb # WIP
    - app/services/kps/omu/kimlik.rb # WIP
    - Vagrantfile
