# Parallel Jobs Workflow

# environment variables
postgres_environment: &postgres_environment
  environment:
    POSTGRES_DB: nokul_test
    POSTGRES_USER: nokul
    POSTGRES_PASSWORD: nokul
rails_environment: &rails_environment
  environment:
    TZ: '/usr/share/zoneinfo/Asia/Istanbul'
    RAILS_ENV: test
    RACK_ENV: test
    RDS_USERNAME: nokul
    RDS_PASSWORD: nokul
    RDS_HOSTNAME: localhost
    RDS_PORT: 5432
    BUNDLE_JOBS: 4

# cache keys
restore_bundle_keys: &restore_bundle_keys
  keys:
    - nokul-bundle-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
    - nokul-bundle-{{ checksum "Gemfile.lock" }}
restore_yarn_keys: &restore_yarn_keys
  keys:
    - nokul-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
    - nokul-yarn-{{ checksum "yarn.lock" }}
save_bundle_keys: &save_bundle_keys
  key: nokul-bundle-{{ checksum "Gemfile.lock" }}
  paths:
    - vendor/bundle
save_bundle_branch_keys: &save_bundle_branch_keys
  key: nokul-bundle-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
  paths:
    - vendor/bundle
save_yarn_keys: &save_yarn_keys
  key: nokul-yarn-{{ checksum "yarn.lock" }}
  paths:
    - node_modules/
save_yarn_branch_keys: &save_yarn_branch_keys
  key: nokul-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
  paths:
    - node_modules/

# build jobs
version: 2
jobs:
  build_2_4_4:
    docker:
      - image: circleci/ruby:2.4.4-node-browsers
        <<: *rails_environment
      - image: circleci/postgres:9.5.14-alpine
        <<: *postgres_environment
    environment:
      CUSTOM_RUBY_VERSION: 2.4.4
    steps:
      - checkout
      - restore_cache:
          <<: *restore_bundle_keys
      - run: bundle install --path vendor/bundle
      - save_cache:
          <<: *save_bundle_keys
      - save_cache:
          <<: *save_bundle_branch_keys
      - restore_cache:
          <<: *restore_yarn_keys
      - run: bin/yarn install
      - save_cache:
          <<: *save_yarn_keys
      - save_cache:
          <<: *save_yarn_branch_keys
      - run: bundle exec rake quality:rails
      - run: bundle exec rake security:all
      - run: bundle exec rake db:migrate
      - run: bundle exec rake test
  build_2_5_1:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
        <<: *rails_environment
      - image: circleci/postgres:9.6.10-alpine
        <<: *postgres_environment
    environment:
      CUSTOM_RUBY_VERSION: 2.5.1
    steps:
      - checkout
      - restore_cache:
          <<: *restore_bundle_keys
      - run: bundle install --path vendor/bundle
      - save_cache:
          <<: *save_bundle_keys
      - save_cache:
          <<: *save_bundle_branch_keys
      - restore_cache:
          <<: *restore_yarn_keys
      - run: bin/yarn install
      - save_cache:
          <<: *save_yarn_keys
      - save_cache:
          <<: *save_yarn_branch_keys
      - run: bundle exec rake quality:rails
      - run: bundle exec rake security:all
      - run: bundle exec rake db:migrate
      - run: bundle exec rake test
  build_2_6_0_preview2:
    docker:
      - image: circleci/ruby:2.6.0-preview2-node-browsers
        <<: *rails_environment
      - image: circleci/postgres:10.5-alpine
        <<: *postgres_environment
    environment:
      CUSTOM_RUBY_VERSION: 2.6.0-preview2
    steps:
      - checkout
      - restore_cache:
          <<: *restore_bundle_keys
      - run: bundle install --path vendor/bundle
      - save_cache:
          <<: *save_bundle_keys
      - save_cache:
          <<: *save_bundle_branch_keys
      - restore_cache:
          <<: *restore_yarn_keys
      - run: bin/yarn install
      - save_cache:
          <<: *save_yarn_keys
      - save_cache:
          <<: *save_yarn_branch_keys
      - run: bundle exec rake quality:rails
      - run: bundle exec rake security:all
      - run: bundle exec rake db:migrate
      - run: bundle exec rake test

# build flow
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build_2_4_4
      - build_2_5_1
      - build_2_6_0_preview2
      - deploy:
          requires:
            - build_2_5_1
          filters:
            branches:
              only: master
