# frozen_string_literal: true

require 'pathname'

PLUGINS_DIR = Pathname.new File.expand_path('..', __dir__)

source 'https://rubygems.org'

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gemspec

group :test do
  gem 'minitest-focus'
  gem 'rails', github: 'rails/rails'
end
