# frozen_string_literal: true

require 'pathname'

PLUGINS_DIR = Pathname.new '..'

source 'https://rubygems.org'
ruby File.read(File.expand_path('.ruby-version', __dir__))

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gemspec

group :test do
  gem 'minitest-focus'
  gem 'rails', github: 'rails/rails'
end
