# frozen_string_literal: true

require_relative 'units/concerns'
require_relative 'units/src'
require_relative 'units/raw'
require_relative 'units/coder'

module Nokul
  module Tenant
    module Units
      RESOURCE = {
        'raw/yok' => Raw::YOKMany,
        'raw/det' => Raw::DETMany,

        'src/yok' => Src::YOKMany,
        'src/det' => Src::DETMany,
        'src/uni' => Src::UNIMany,
        'src/all' => Src::ALLMany
      }.freeze

      def self.resource?(resource)
        RESOURCE.key? resource
      end

      def self.method_missing(method, resource, *args)
        if (klass = RESOURCE[resource.to_s])
          return klass.send(method, *args) if klass.respond_to? method
          return klass.load_source.send(method, *args) if klass.method_defined? method
        end

        super
      end

      def self.respond_to_missing?(method, include_private: false)
        super
      end

      def self.reproduce_src(quiet: false)
        states = []

        states += %w[raw/yok raw/det].map do |resource|
          warn "Getting changes of #{resource}" unless quiet
          update(resource).store quiet: quiet, comment: <<~COMMENT
            REFER DOCUMENTATION TO EDIT THIS FILE.  PLEASE NOTE THAT:

            - EXISTING RAW ATTRIBUTES WILL NORMALLY BE OVERWRITTEN ON NEXT UPDATE.
            - COMMENTS AND EXTRA BLANK LINES WILL NOT BE PRESERVED.
          COMMENT
        end

        states.any? { |state| state } # signal any change
      end

      def self.reproduce_all(quiet: false)
        states = []

        states.append reproduce_src quiet: quiet

        warn 'Updating src/all' unless quiet
        states.append produce('src/all').store quiet: quiet, comment: <<~COMMENT
          AUTOGENERATED FROM SOURCES.  DO NOT EDIT!
        COMMENT

        states.any? { |state| state } # signal any change
      end

      class << self
        alias reproduce reproduce_all
      end
    end
  end
end
