<%
  name = if File.exist?(manifest = Rails.root.join('app.json'))
           require 'json'
           JSON.parse(File.read(manifest)).fetch 'name'
         else
           Rails.application.class.parent.to_s.underscore
         end
  url = "postgresql://#{name}:#{name}@localhost/#{name}_%<environment>s"
%>

default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  url: <%= format url, environment: 'development' %>

test:
  <<: *default
  url: <%= format url, environment: 'test' %>

production: &production
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 40) %>
  prepared_statements: true

beta:
  <<: *production
