<% name = Rails.application.appname
   url = "postgresql://#{name}:#{name}@localhost/#{name}_%{environment}" %>

default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  url: <%= format url, environment: 'development' %>

test:
  <<: *default
  url: <%= format url, environment: 'test' %>

production: &production
  <<: *default
  database: nokul_database
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 40) %>

beta:
  <<: *production
  database: nokul-develop-database
