default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>

development:
  <<: *default
  database: nokul_dev

test:
  <<: *default
  pool: 5
  database: nokul_test

production: &production
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  pool: 40
  timeout: 5000

beta:
  <<: *production
