<% name = Rails.application.appname
   url = "postgresql://#{name}:#{name}@localhost/#{name}_%{environment}" %>

default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  url: <%= ENV.fetch('DEVELOPMENT_DATABASE_URL', format(url, environment: 'development')) %>

test:
  <<: *default
  url: <%= ENV.fetch('TEST_DATABASE_URL', format(url, environment: 'test')) %>

production: &production
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 40) %>

beta:
  <<: *production
