<% name = Rails.application.class.parent.to_s.underscore %>

default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  url: <%= 'postgresql://' + name + ':' + name + '@' + 'localhost' + '/' + name + '_development' %>

test:
  <<: *default
  url: <%= 'postgresql://' + name + ':' + name + '@' + 'localhost' + '/' + name + '_test' %>

production: &production
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 40) %>
  prepared_statements: true

beta:
  <<: *production
