# frozen_string_literal: true

require 'pathname'

PLUGINS_DIR = Pathname.new File.expand_path('../..', __dir__)

source 'https://rubygems.org'
ruby File.read('.ruby-version')

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gemspec

gem 'nokul-support', path: PLUGINS_DIR.join('support')

group :test do
  gem 'minitest-focus'
  gem 'rails', github: 'rails/rails'
end
